### PR TITLE
Fixes #15 when plotting trees with linear=TRUE and single unique Y leaf value

### LINKED ISSUE #15: Plotting with linear = TRUE sometimes fails
When plotting a model with linFeats = TRUE, I get the error: `Error in elnet(x, is.sparse, ix, yx, y, weights, offset, type.gaussian, y is constant; gaussian glment fails at the standardization step`

Here is code that produces it, largely taken from an example in `?forestry`. 

```
n <- c(100)
a <- rnorm(n)
b <- rnorm(n)
c <- rnorm(n)
y <- 4*a + 5.5*b - .78*c
x <- data.frame(a,b,c)

forest <- forestry(
  x,
  y,
  ntree = 10,
  replace = TRUE,
  maxDepth = 100,
  nodesizeStrictSpl = 1,
  nodesizeStrictAvg = 1,
  nthread = 2,
  linear = TRUE
)

plot(forest)
```

### LINKED ISSUE #16: R crashes when linFeats is a singleton
Here's an example. Note that this code will cause R to crash. 

```
n <- c(100)
a <- rnorm(n)
b <- rnorm(n)
c <- rnorm(n)
y <- 4*a + 5.5*b - .78*c
x <- data.frame(a,b,c)

forest <- forestry(
  x,
  y,
  ntree = 10,
  replace = TRUE,
  maxDepth = 100,
  nodesizeStrictSpl = 10,
  nodesizeStrictAvg = 10,
  nthread = 2,
  linear = TRUE,
  linFeats = 1
)

predict(forest, aggregation = "oob")
```

### PR DESCRIPTION
**Pull request by linanqiu**
Fixes #15when plotting trees with linear=TRUE and single unique Y leaf value

### CODE REVIEW

File: tests/testthat/test-plottree.R [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    replace = TRUE,
+    maxDepth = 100,
+    nodesizeStrictSpl = 1,
+    nodesizeStrictAvg = 1,
+    nthread = 2,
+    linear = TRUE
+  )
+
+  # expect_error with regexp = NA asserts that there should be no errors. I know wtf.
+  expect_error(plot(forest), regexp = NA)
```
Comment (sjsw) [inline tests/testthat/test-plottree.R:24]: There is is also expect_silent, although it differs from this a bit as it will fail if there are messages or warnings.
